const fs = require("fs");
const path = require("path");

const rawGroups = [
  // Term 2 CS
  {
    groupName: "2CS1",
    semester: 2,
    department: "CS",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 1, code: "EBA1204", title: "Calculus II" },
      { day: "Sa", period: 2, code: "CCS1302", title: "Problem Solving and Programming" },
      { day: "Su", period: 2, code: "UNR1407", title: "Academic Writing" },
      { day: "Su", period: 3, code: "UNR2101", title: "Communication and Presentation Skills" },
      { day: "Su", period: 4, code: "CCS1302", title: "Problem Solving and Programming" },
      { day: "Mo", period: 2, code: "CCS1001", title: "Discrete Structures" },
      { day: "Mo", period: 3, code: "CCS1001", title: "Discrete Structures" },
      { day: "Mo", period: 4, code: "UNR1407", title: "Academic Writing" },
      { day: "We", period: 2, code: "UNR2101", title: "Communication and Presentation Skills" },
      { day: "We", period: 3, code: "EBA1106", title: "Advanced Physics" },
      { day: "We", period: 4, code: "EBA1106", title: "Advanced Physics" },
      { day: "Th", period: 3, code: "CNC1401", title: "Entrepreneurship Skills" },
      { day: "Th", period: 4, code: "EBA1204", title: "Calculus II" },
      { day: "Th", period: 6, code: "CCS1302", title: "Problem Solving and Programming" },
    ],
  },
  {
    groupName: "2CS2-Science",
    semester: 2,
    department: "CS",
    subGroup: "2-Science",
    slots: [
      { day: "Sa", period: 1, code: "CCS1302", title: "Problem Solving and Programming" },
      { day: "Sa", period: 2, code: "EBA1110", title: "Physics" },
      { day: "Sa", period: 3, code: "EBA1203", title: "Calculus I" },
      { day: "Su", period: 2, code: "UNR1407", title: "Academic Writing" },
      { day: "Su", period: 3, code: "UNR2101", title: "Communication and Presentation Skills" },
      { day: "Su", period: 5, code: "EBA1110", title: "Physics" },
      { day: "Mo", period: 3, code: "CCS1001", title: "Discrete Structures" },
      { day: "Mo", period: 4, code: "UNR1407", title: "Academic Writing" },
      { day: "Mo", period: 6, code: "CCS1302", title: "Problem Solving and Programming" },
      { day: "We", period: 2, code: "UNR2101", title: "Communication and Presentation Skills" },
      { day: "We", period: 3, code: "CCS1302", title: "Problem Solving and Programming" },
      { day: "Th", period: 2, code: "CCS1001", title: "Discrete Structures" },
      { day: "Th", period: 3, code: "CNC1401", title: "Entrepreneurship Skills" },
      { day: "Th", period: 4, code: "EBA1203", title: "Calculus I" },
    ],
  },
  {
    groupName: "2CS3",
    semester: 2,
    department: "CS",
    subGroup: "3",
    slots: [
      { day: "Sa", period: 2, code: "EBA1204", title: "Calculus II" },
      { day: "Su", period: 2, code: "CCS1001", title: "Discrete Structures" },
      { day: "We", period: 2, code: "EBA1106", title: "Advanced Physics" },
      { day: "We", period: 4, code: "CCS1001", title: "Discrete Structures" },
      { day: "We", period: 5, code: "EBA1106", title: "Advanced Physics" },
      { day: "Th", period: 3, code: "EBA1204", title: "Calculus II" },
    ],
  },

  // Term 3 CS (3CS1 to 3CS17)
  {
    groupName: "3CS1",
    semester: 3,
    department: "CS",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 1, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Sa", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 1, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Su", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 3, code: "CIS2101", title: "Database Systems" },
      { day: "Mo", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 4, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 2, code: "CIS2101", title: "Database Systems" },
      { day: "Tu", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "Tu", period: 4, code: "EBA2203", title: "Probability & Statistics" },
      { day: "We", period: 1, code: "CCS2201", title: "Introduction to Networks" },
      { day: "We", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "We", period: 5, code: "CCS2102", title: "Digital Logic Design" },
    ],
  },
  {
    groupName: "3CS2",
    semester: 3,
    department: "CS",
    subGroup: "2",
    slots: [
      { day: "Sa", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Sa", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 2, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Su", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 4, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 1, code: "CIS2101", title: "Database Systems" },
      { day: "Mo", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "Mo", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 1, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Tu", period: 3, code: "CIS2101", title: "Database Systems" },
      { day: "We", period: 2, code: "CCS2201", title: "Introduction to Networks" },
      { day: "We", period: 3, code: "EBA2204", title: "Linear Algebra" },
    ],
  },
  {
    groupName: "3CS3",
    semester: 3,
    department: "CS",
    subGroup: "3",
    slots: [
      { day: "Su", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Su", period: 5, code: "CIS2101", title: "Database Systems" },
      { day: "Mo", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Tu", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Tu", period: 4, code: "CIS2101", title: "Database Systems" },
      { day: "Tu", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "We", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "We", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Th", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Th", period: 3, code: "CCS2201", title: "Introduction to Networks" },
    ],
  },
  {
    groupName: "3CS4",
    semester: 3,
    department: "CS",
    subGroup: "4",
    slots: [
      { day: "Sa", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Sa", period: 4, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Sa", period: 5, code: "CIS2101", title: "Database Systems" },
      { day: "Su", period: 1, code: "EBA2204", title: "Linear Algebra" },
      { day: "Su", period: 2, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Su", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Mo", period: 4, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 5, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 5, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Tu", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 2, code: "CIS2101", title: "Database Systems" },
      { day: "We", period: 3, code: "EBA2204", title: "Linear Algebra" },
    ],
  },
  {
    groupName: "3CS5",
    semester: 3,
    department: "CS",
    subGroup: "5",
    slots: [
      { day: "Sa", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Sa", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Sa", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Sa", period: 5, code: "CIS2101", title: "Database Systems" },
      { day: "Su", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "Su", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 4, code: "EBA2204", title: "Linear Algebra" },
      { day: "Mo", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 2, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Tu", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "We", period: 1, code: "CIS2101", title: "Database Systems" },
      { day: "We", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
    ],
  },
  {
    groupName: "3CS6",
    semester: 3,
    department: "CS",
    subGroup: "6",
    slots: [
      { day: "Sa", period: 2, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Sa", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Sa", period: 4, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 5, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Mo", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "Mo", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 5, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 6, code: "CIS2101", title: "Database Systems" },
      { day: "We", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "We", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "We", period: 4, code: "CIS2101", title: "Database Systems" },
    ],
  },
  {
    groupName: "3CS7",
    semester: 3,
    department: "CS",
    subGroup: "7",
    slots: [
      { day: "Sa", period: 1, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Sa", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Sa", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "Su", period: 1, code: "CIS2101", title: "Database Systems" },
      { day: "Su", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 3, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Mo", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 2, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "Tu", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "We", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 4, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "We", period: 6, code: "CIS2101", title: "Database Systems" },
    ],
  },
  {
    groupName: "3CS8",
    semester: 3,
    department: "CS",
    subGroup: "8",
    slots: [
      { day: "Sa", period: 5, code: "EBA2204", title: "Linear Algebra" },
      { day: "Sa", period: 6, code: "CIS2101", title: "Database Systems" },
      { day: "Su", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 4, code: "CIS2101", title: "Database Systems" },
      { day: "Su", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Mo", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Tu", period: 1, code: "EBA2204", title: "Linear Algebra" },
      { day: "Tu", period: 2, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "We", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "We", period: 3, code: "CCS2201", title: "Introduction to Networks" },
      { day: "We", period: 4, code: "CCS2102", title: "Digital Logic Design" },
    ],
  },
  {
    groupName: "3CS9",
    semester: 3,
    department: "CS",
    subGroup: "9",
    slots: [
      { day: "Sa", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Sa", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Sa", period: 6, code: "EBA2204", title: "Linear Algebra" },
      { day: "Su", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Su", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Mo", period: 4, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Tu", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "Tu", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "We", period: 3, code: "CIS2101", title: "Database Systems" },
      { day: "We", period: 5, code: "CIS2101", title: "Database Systems" },
    ],
  },
  {
    groupName: "3CS10",
    semester: 3,
    department: "CS",
    subGroup: "10",
    slots: [
      { day: "Sa", period: 1, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Sa", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Sa", period: 3, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Su", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 5, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Su", period: 6, code: "CIS2101", title: "Database Systems" },
      { day: "Mo", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "We", period: 4, code: "CIS2101", title: "Database Systems" },
      { day: "We", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Th", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "Th", period: 3, code: "CCS2102", title: "Digital Logic Design" },
    ],
  },
  {
    groupName: "3CS11",
    semester: 3,
    department: "CS",
    subGroup: "11",
    slots: [
      { day: "Sa", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Sa", period: 2, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Sa", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Tu", period: 1, code: "CIS2101", title: "Database Systems" },
      { day: "Tu", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Tu", period: 3, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Th", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "Th", period: 4, code: "EBA2204", title: "Linear Algebra" },
      { day: "Th", period: 5, code: "CIS2101", title: "Database Systems" },
    ],
  },
  {
    groupName: "3CS12",
    semester: 3,
    department: "CS",
    subGroup: "12",
    slots: [
      { day: "Sa", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Sa", period: 4, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Su", period: 1, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 1, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Mo", period: 2, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "We", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "We", period: 4, code: "EBA2204", title: "Linear Algebra" },
      { day: "Th", period: 3, code: "CIS2101", title: "Database Systems" },
      { day: "Th", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Th", period: 6, code: "CIS2101", title: "Database Systems" },
    ],
  },
  {
    groupName: "3CS13",
    semester: 3,
    department: "CS",
    subGroup: "13",
    slots: [
      { day: "Sa", period: 1, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Sa", period: 2, code: "CIS2101", title: "Database Systems" },
      { day: "Sa", period: 3, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Mo", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 4, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Tu", period: 5, code: "CIS2101", title: "Database Systems" },
      { day: "We", period: 1, code: "EBA2204", title: "Linear Algebra" },
      { day: "We", period: 2, code: "CCS2201", title: "Introduction to Networks" },
      { day: "We", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Th", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Th", period: 3, code: "EBA2204", title: "Linear Algebra" },
    ],
  },
  {
    groupName: "3CS14",
    semester: 3,
    department: "CS",
    subGroup: "14",
    slots: [
      { day: "Sa", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Sa", period: 4, code: "CIS2101", title: "Database Systems" },
      { day: "Su", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "Su", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Mo", period: 4, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 5, code: "CIS2101", title: "Database Systems" },
      { day: "Mo", period: 6, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 3, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 4, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Th", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Th", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "Th", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
    ],
  },
  {
    groupName: "3CS15",
    semester: 3,
    department: "CS",
    subGroup: "15",
    slots: [
      { day: "Sa", period: 2, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Sa", period: 3, code: "CIS2101", title: "Database Systems" },
      { day: "Sa", period: 4, code: "EBA2204", title: "Linear Algebra" },
      { day: "Sa", period: 5, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "Su", period: 4, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Su", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Mo", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Mo", period: 5, code: "CIS2101", title: "Database Systems" },
      { day: "Tu", period: 1, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 2, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Tu", period: 5, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Th", period: 1, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Th", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
    ],
  },
  {
    groupName: "3CS16",
    semester: 3,
    department: "CS",
    subGroup: "16",
    slots: [
      { day: "Sa", period: 2, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Sa", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Sa", period: 4, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 1, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Su", period: 2, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Su", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Mo", period: 2, code: "CIS2101", title: "Database Systems" },
      { day: "Mo", period: 3, code: "EBA2204", title: "Linear Algebra" },
      { day: "Mo", period: 5, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Tu", period: 2, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Tu", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 2, code: "CIS2101", title: "Database Systems" },
      { day: "We", period: 4, code: "EBA2204", title: "Linear Algebra" },
    ],
  },
  {
    groupName: "3CS17",
    semester: 3,
    department: "CS",
    subGroup: "17",
    slots: [
      { day: "Sa", period: 1, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Sa", period: 2, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Sa", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 2, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Su", period: 3, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "Su", period: 4, code: "CIS2101", title: "Database Systems" },
      { day: "Mo", period: 1, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Mo", period: 2, code: "EBA2204", title: "Linear Algebra" },
      { day: "Tu", period: 1, code: "EBA2204", title: "Linear Algebra" },
      { day: "Tu", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "Tu", period: 6, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 3, code: "CCS2102", title: "Digital Logic Design" },
      { day: "We", period: 4, code: "CCS2303", title: "Object Oriented Programming" },
      { day: "We", period: 6, code: "CIS2101", title: "Database Systems" },
      { day: "Th", period: 1, code: "CCS2201", title: "Introduction to Networks" },
      { day: "Th", period: 3, code: "EBA2203", title: "Probability & Statistics" },
      { day: "Th", period: 4, code: "CIS2101", title: "Database Systems" },
    ],
  },

  // Term 4 CS (4CS1 to 4CS4)
  {
    groupName: "4CS1",
    semester: 4,
    department: "CS",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 3, code: "CCS2103", title: "Introduction to Computer Architecture" },
      { day: "Sa", period: 4, code: "CCS2401", title: "Data Structures and Algorithms" },
      { day: "Sa", period: 5, code: "CSE2001", title: "Introduction to Software Engineering" },
      { day: "Su", period: 1, code: "CCS2304", title: "Advanced Programming Applications" },
      { day: "Su", period: 2, code: "CCS2304", title: "Advanced Programming Applications" },
      { day: "Su", period: 3, code: "CSE2001", title: "Introduction to Software Engineering" },
      { day: "Mo", period: 6, code: "CCY2001", title: "Introduction to Cybersecurity" },
      { day: "Tu", period: 3, code: "CCS2401", title: "Data Structures and Algorithms" },
      { day: "We", period: 2, code: "CCS2103", title: "Introduction to Computer Architecture" },
      { day: "We", period: 3, code: "CCS2305", title: "Web Programming" },
      { day: "We", period: 4, code: "CCS2305", title: "Web Programming" },
      { day: "We", period: 5, code: "CCY2001", title: "Introduction to Cybersecurity" },
    ],
  },
  {
    groupName: "4CS2",
    semester: 4,
    department: "CS",
    subGroup: "2",
    slots: [
      { day: "Sa", period: 2, code: "CCS2103", title: "Introduction to Computer Architecture" },
      { day: "Sa", period: 3, code: "CCS2304", title: "Advanced Programming Applications" },
      { day: "Sa", period: 4, code: "CSE2001", title: "Introduction to Software Engineering" },
      { day: "Sa", period: 5, code: "CCS2401", title: "Data Structures and Algorithms" },
      { day: "Su", period: 1, code: "CCS2304", title: "Advanced Programming Applications" },
      { day: "Su", period: 2, code: "CSE2001", title: "Introduction to Software Engineering" },
      { day: "Mo", period: 5, code: "CCY2001", title: "Introduction to Cybersecurity" },
      { day: "Tu", period: 2, code: "CCS2401", title: "Data Structures and Algorithms" },
      { day: "Tu", period: 3, code: "CCS2305", title: "Web Programming" },
      { day: "We", period: 3, code: "CCS2103", title: "Introduction to Computer Architecture" },
      { day: "We", period: 5, code: "CCS2305", title: "Web Programming" },
      { day: "We", period: 6, code: "CCY2001", title: "Introduction to Cybersecurity" },
    ],
  },
  {
    groupName: "4CS3",
    semester: 4,
    department: "CS",
    subGroup: "3",
    slots: [
      { day: "Sa", period: 1, code: "CCS2103", title: "Introduction to Computer Architecture" },
      { day: "Sa", period: 3, code: "CCY2001", title: "Introduction to Cybersecurity" },
      { day: "Su", period: 2, code: "CCS2304", title: "Advanced Programming Applications" },
      { day: "Su", period: 3, code: "CCS2401", title: "Data Structures and Algorithms" },
      { day: "Su", period: 5, code: "CCY2001", title: "Introduction to Cybersecurity" },
      { day: "Tu", period: 1, code: "CCS2401", title: "Data Structures and Algorithms" },
      { day: "Tu", period: 2, code: "CCS2305", title: "Web Programming" },
      { day: "We", period: 3, code: "CSE2001", title: "Introduction to Software Engineering" },
      { day: "We", period: 4, code: "CCS2305", title: "Web Programming" },
      { day: "We", period: 5, code: "CSE2001", title: "Introduction to Software Engineering" },
      { day: "Th", period: 2, code: "CCS2103", title: "Introduction to Computer Architecture" },
      { day: "Th", period: 3, code: "CCS2304", title: "Advanced Programming Applications" },
    ],
  },
  {
    groupName: "4CS4",
    semester: 4,
    department: "CS",
    subGroup: "4",
    slots: [
      { day: "Sa", period: 1, code: "CCS2103", title: "Introduction to Computer Architecture" },
      { day: "Sa", period: 2, code: "CCY2001", title: "Introduction to Cybersecurity" },
      { day: "Sa", period: 3, code: "CSE2001", title: "Introduction to Software Engineering" },
      { day: "Su", period: 3, code: "CCS2304", title: "Advanced Programming Applications" },
      { day: "Su", period: 4, code: "CCS2401", title: "Data Structures and Algorithms" },
      { day: "Su", period: 6, code: "CCY2001", title: "Introduction to Cybersecurity" },
      { day: "Tu", period: 1, code: "CCS2401", title: "Data Structures and Algorithms" },
      { day: "Tu", period: 2, code: "CCS2305", title: "Web Programming" },
      { day: "We", period: 2, code: "CSE2001", title: "Introduction to Software Engineering" },
      { day: "We", period: 4, code: "CCS2305", title: "Web Programming" },
      { day: "Th", period: 1, code: "CCS2103", title: "Introduction to Computer Architecture" },
      { day: "Th", period: 2, code: "CCS2304", title: "Advanced Programming Applications" },
    ],
  },

  // Term 5 CS
  {
    groupName: "5CS1",
    semester: 5,
    department: "CS",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 1, code: "EBA3202", title: "Differential Equations" },
      { day: "Sa", period: 2, code: "CCS3202", title: "Systems Programming" },
      { day: "Su", period: 1, code: "CCS3402", title: "Theory of Computation" },
      { day: "Su", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Mo", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 6, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Tu", period: 3, code: "EBA3202", title: "Differential Equations" },
      { day: "Tu", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 5, code: "CCS3402", title: "Theory of Computation" },
      { day: "Th", period: 5, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Th", period: 6, code: "CCS3202", title: "Systems Programming" },
    ],
  },
  {
    groupName: "5CS2",
    semester: 5,
    department: "CS",
    subGroup: "2",
    slots: [
      { day: "Su", period: 1, code: "EBA3202", title: "Differential Equations" },
      { day: "Su", period: 2, code: "CCS3402", title: "Theory of Computation" },
      { day: "Mo", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Mo", period: 3, code: "CCS3202", title: "Systems Programming" },
      { day: "Mo", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 4, code: "EBA3202", title: "Differential Equations" },
      { day: "Tu", period: 6, code: "CCS3402", title: "Theory of Computation" },
      { day: "We", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "We", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 5, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Th", period: 5, code: "CCS3202", title: "Systems Programming" },
      { day: "Th", period: 6, code: "CCS3203", title: "Operating Systems" },
    ],
  },

  // Term 5 IS
  {
    groupName: "5IS",
    semester: 5,
    department: "IS",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Sa", period: 5, code: "CNC3402", title: "Introduction to Accounting" },
      { day: "Sa", period: 6, code: "CNC3402", title: "Introduction to Accounting" },
      { day: "Mo", period: 2, code: "CIS3001", title: "Systems Analysis & Design" },
      { day: "Mo", period: 3, code: "CIS3002", title: "Information Systems Theory & Practice" },
      { day: "Mo", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Tu", period: 2, code: "CIS3001", title: "Systems Analysis & Design" },
      { day: "Tu", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Tu", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 4, code: "CIS3002", title: "Information Systems Theory & Practice" },
      { day: "We", period: 5, code: "CCS3203", title: "Operating Systems" },
    ],
  },

  // Term 5 SE (5SE1 to 5SE7)
  {
    groupName: "5SE1",
    semester: 5,
    department: "SE",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 1, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Sa", period: 2, code: "EBA3202", title: "Differential Equations" },
      { day: "Sa", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 2, code: "EBA3202", title: "Differential Equations" },
      { day: "Mo", period: 3, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Tu", period: 2, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Tu", period: 3, code: "CSE3402", title: "Project Management" },
      { day: "We", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "We", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Th", period: 2, code: "CSE3402", title: "Project Management" },
      { day: "Th", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
    ],
  },
  {
    groupName: "5SE2",
    semester: 5,
    department: "SE",
    subGroup: "2",
    slots: [
      { day: "Su", period: 1, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Su", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 1, code: "EBA3202", title: "Differential Equations" },
      { day: "Mo", period: 2, code: "CSE3402", title: "Project Management" },
      { day: "Mo", period: 3, code: "EBA3202", title: "Differential Equations" },
      { day: "Tu", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 3, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "We", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "We", period: 4, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Th", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "Th", period: 4, code: "CSE3402", title: "Project Management" },
      { day: "Th", period: 5, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
    ],
  },
  {
    groupName: "5SE3",
    semester: 5,
    department: "SE",
    subGroup: "3",
    slots: [
      { day: "Sa", period: 3, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Sa", period: 5, code: "CCS3203", title: "Operating Systems" },
      { day: "Su", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "Su", period: 2, code: "EBA3202", title: "Differential Equations" },
      { day: "Su", period: 3, code: "CSE3402", title: "Project Management" },
      { day: "Mo", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 2, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "We", period: 1, code: "EBA3202", title: "Differential Equations" },
      { day: "We", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "We", period: 3, code: "CSE3402", title: "Project Management" },
      { day: "Th", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 3, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
    ],
  },
  {
    groupName: "5SE4",
    semester: 5,
    department: "SE",
    subGroup: "4",
    slots: [
      { day: "Sa", period: 1, code: "CSE3402", title: "Project Management" },
      { day: "Sa", period: 2, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Su", period: 3, code: "EBA3202", title: "Differential Equations" },
      { day: "Su", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 1, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Mo", period: 2, code: "EBA3202", title: "Differential Equations" },
      { day: "Tu", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 4, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Th", period: 2, code: "CSE3402", title: "Project Management" },
      { day: "Th", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
    ],
  },
  {
    groupName: "5SE5",
    semester: 5,
    department: "SE",
    subGroup: "5",
    slots: [
      { day: "Sa", period: 2, code: "CSE3402", title: "Project Management" },
      { day: "Sa", period: 3, code: "EBA3202", title: "Differential Equations" },
      { day: "Sa", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Su", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "Su", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 1, code: "EBA3202", title: "Differential Equations" },
      { day: "Mo", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 4, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Tu", period: 5, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Th", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 3, code: "CSE3402", title: "Project Management" },
      { day: "Th", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
    ],
  },
  {
    groupName: "5SE6",
    semester: 5,
    department: "SE",
    subGroup: "6",
    slots: [
      { day: "Sa", period: 2, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Sa", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 2, code: "EBA3202", title: "Differential Equations" },
      { day: "Mo", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Tu", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Tu", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "We", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 2, code: "EBA3202", title: "Differential Equations" },
      { day: "Th", period: 1, code: "CSE3402", title: "Project Management" },
      { day: "Th", period: 2, code: "CSE3402", title: "Project Management" },
      { day: "Th", period: 3, code: "CSE3101", title: "Software Requirements and Specifications" },
    ],
  },
  {
    groupName: "5SE7",
    semester: 5,
    department: "SE",
    subGroup: "7",
    slots: [
      { day: "Sa", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Mo", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 3, code: "EBA3202", title: "Differential Equations" },
      { day: "Mo", period: 4, code: "EBA3202", title: "Differential Equations" },
      { day: "Tu", period: 4, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "Tu", period: 6, code: "CSE3402", title: "Project Management" },
      { day: "We", period: 2, code: "CSE3101", title: "Software Requirements and Specifications" },
      { day: "We", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Th", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "Th", period: 2, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 3, code: "CSE3402", title: "Project Management" },
    ],
  },

  // Term 5 CY (5CY1 to 5CY7)
  {
    groupName: "5CY1",
    semester: 5,
    department: "CY",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 3, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Sa", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Sa", period: 5, code: "CCY3101", title: "Software Security" },
      { day: "Su", period: 2, code: "CCY3101", title: "Software Security" },
      { day: "Su", period: 4, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Mo", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Mo", period: 6, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Tu", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "Th", period: 2, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Th", period: 3, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
    ],
  },
  {
    groupName: "5CY2",
    semester: 5,
    department: "CY",
    subGroup: "2",
    slots: [
      { day: "Su", period: 2, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Su", period: 3, code: "CCY3101", title: "Software Security" },
      { day: "Su", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Mo", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 5, code: "CCY3101", title: "Software Security" },
      { day: "Tu", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 6, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "We", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "Th", period: 3, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Th", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 5, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Th", period: 6, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
    ],
  },
  {
    groupName: "5CY3",
    semester: 5,
    department: "CY",
    subGroup: "3",
    slots: [
      { day: "Sa", period: 3, code: "CCY3101", title: "Software Security" },
      { day: "Sa", period: 5, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Su", period: 4, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Su", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Su", period: 6, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Mo", period: 6, code: "CCY3101", title: "Software Security" },
      { day: "We", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Th", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Th", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 6, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
    ],
  },
  {
    groupName: "5CY4",
    semester: 5,
    department: "CY",
    subGroup: "4",
    slots: [
      { day: "Sa", period: 6, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Su", period: 4, code: "CCY3101", title: "Software Security" },
      { day: "Su", period: 5, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Mo", period: 5, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Mo", period: 6, code: "CCY3101", title: "Software Security" },
      { day: "We", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 2, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Th", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Th", period: 5, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
    ],
  },
  {
    groupName: "5CY5",
    semester: 5,
    department: "CY",
    subGroup: "5",
    slots: [
      { day: "Sa", period: 4, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Sa", period: 5, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Sa", period: 6, code: "CCY3101", title: "Software Security" },
      { day: "Su", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Su", period: 5, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Mo", period: 4, code: "CCY3101", title: "Software Security" },
      { day: "Mo", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Tu", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 5, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "We", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 6, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
    ],
  },
  {
    groupName: "5CY6",
    semester: 5,
    department: "CY",
    subGroup: "6",
    slots: [
      { day: "Sa", period: 4, code: "CCY3101", title: "Software Security" },
      { day: "Sa", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Sa", period: 6, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Su", period: 3, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Su", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 4, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Mo", period: 5, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Mo", period: 6, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Tu", period: 5, code: "CCY3101", title: "Software Security" },
      { day: "Tu", period: 6, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "We", period: 3, code: "CCS3203", title: "Operating Systems" },
    ],
  },
  {
    groupName: "5CY7",
    semester: 5,
    department: "CY",
    subGroup: "7",
    slots: [
      { day: "Sa", period: 4, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Sa", period: 5, code: "CCS3203", title: "Operating Systems" },
      { day: "Sa", period: 6, code: "CCY3101", title: "Software Security" },
      { day: "Su", period: 5, code: "CCY3501", title: "Cybersecurity Law and Ethics" },
      { day: "Su", period: 6, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "Mo", period: 2, code: "CCY3101", title: "Software Security" },
      { day: "Mo", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Mo", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Tu", period: 3, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Tu", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Tu", period: 5, code: "CCY3002", title: "Introduction to Cryptography" },
      { day: "We", period: 3, code: "CCS3203", title: "Operating Systems" },
    ],
  },

  // Term 5 AI (5AI1 to 5AI3)
  {
    groupName: "5AI1",
    semester: 5,
    department: "AI",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 4, code: "CAI3401", title: "Fundamentals of Robotics" },
      { day: "Sa", period: 5, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Su", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "Su", period: 2, code: "EBA3201", title: "Advanced Statistics" },
      { day: "Su", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Mo", period: 2, code: "CAI3401", title: "Fundamentals of Robotics" },
      { day: "Mo", period: 3, code: "CAI3002", title: "Mathematical Foundations of AI" },
      { day: "Mo", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Mo", period: 5, code: "EBA3201", title: "Advanced Statistics" },
      { day: "Tu", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 6, code: "CAI3002", title: "Mathematical Foundations of AI" },
      { day: "We", period: 6, code: "CCS3203", title: "Operating Systems" },
    ],
  },
  {
    groupName: "5AI2",
    semester: 5,
    department: "AI",
    subGroup: "2",
    slots: [
      { day: "Sa", period: 4, code: "CCS3203", title: "Operating Systems" },
      { day: "Sa", period: 5, code: "CAI3401", title: "Fundamentals of Robotics" },
      { day: "Su", period: 2, code: "EBA3201", title: "Advanced Statistics" },
      { day: "Su", period: 3, code: "EBA3201", title: "Advanced Statistics" },
      { day: "Su", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Mo", period: 3, code: "CAI3401", title: "Fundamentals of Robotics" },
      { day: "Mo", period: 4, code: "CAI3002", title: "Mathematical Foundations of AI" },
      { day: "Mo", period: 5, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 5, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Tu", period: 6, code: "CAI3002", title: "Mathematical Foundations of AI" },
      { day: "We", period: 2, code: "CCS3203", title: "Operating Systems" },
      { day: "We", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
    ],
  },
  {
    groupName: "5AI3",
    semester: 5,
    department: "AI",
    subGroup: "3",
    slots: [
      { day: "Sa", period: 1, code: "CCS3203", title: "Operating Systems" },
      { day: "Sa", period: 2, code: "CAI3401", title: "Fundamentals of Robotics" },
      { day: "Sa", period: 3, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Su", period: 4, code: "EBA3201", title: "Advanced Statistics" },
      { day: "Mo", period: 1, code: "CAI3401", title: "Fundamentals of Robotics" },
      { day: "Mo", period: 2, code: "CAI3002", title: "Mathematical Foundations of AI" },
      { day: "Mo", period: 3, code: "CCS3203", title: "Operating Systems" },
      { day: "Tu", period: 2, code: "EBA3201", title: "Advanced Statistics" },
      { day: "Tu", period: 4, code: "CIT3200", title: "Professional Training in Mobile Apps Programming" },
      { day: "Tu", period: 5, code: "CAI3002", title: "Mathematical Foundations of AI" },
      { day: "Th", period: 4, code: "CAI3101", title: "Introduction to Artificial Intelligence" },
      { day: "Th", period: 5, code: "CCS3203", title: "Operating Systems" },
    ],
  },

  // Term 8 SE
  {
    groupName: "8SE1",
    semester: 8,
    department: "SE",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 4, code: "CSE4407", title: "Software Risk Management" },
      { day: "Su", period: 4, code: "CSE4302", title: "Software Quality Assurance" },
      { day: "Su", period: 6, code: "CCS4204", title: "Computer System Security" },
      { day: "Tu", period: 3, code: "CSE4407", title: "Software Risk Management" },
      { day: "Tu", period: 4, code: "CCS4204", title: "Computer System Security" },
      { day: "Tu", period: 5, code: "CSE4401", title: "Software Engineering Process" },
      { day: "Tu", period: 6, code: "CIT4103", title: "Professional Training in Software Testing III" },
      { day: "We", period: 4, code: "CSE4401", title: "Software Engineering Process" },
      { day: "We", period: 6, code: "CSE4302", title: "Software Quality Assurance" },
    ],
  },

  // Term 8 IS
  {
    groupName: "8IS1",
    semester: 8,
    department: "IS",
    subGroup: "1",
    slots: [
      { day: "Sa", period: 4, code: "CIS4104", title: "Distributed Database Systems" },
      { day: "Sa", period: 5, code: "CIT4903", title: "Professional Training in Data Science III" },
      { day: "Sa", period: 6, code: "CIS4104", title: "Distributed Database Systems" },
      { day: "Su", period: 4, code: "CIS4105", title: "Knowledge Management" },
      { day: "Su", period: 6, code: "CCS4204", title: "Computer System Security" },
      { day: "Tu", period: 4, code: "CCS4204", title: "Computer System Security" },
      { day: "We", period: 6, code: "CIS4303", title: "Decision Support Systems" },
      { day: "Th", period: 1, code: "CIS4105", title: "Knowledge Management" },
      { day: "Th", period: 3, code: "CIS4303", title: "Decision Support Systems" },
    ],
  },
];

// Convert slots into group courses
const groupSchedules = rawGroups.map((g) => {
  const courseMap = new Map();
  for (const slot of g.slots) {
    const code = slot.code.toUpperCase().trim();
    if (!courseMap.has(code)) {
      courseMap.set(code, {
        code,
        title: slot.title.trim(),
        slots: [],
      });
    }
    courseMap.get(code).slots.push({
      day: slot.day,
      period: slot.period,
    });
  }

  return {
    groupName: g.groupName,
    semester: g.semester,
    department: g.department,
    subGroup: g.subGroup,
    courses: Array.from(courseMap.values()),
  };
});

const outDir = path.join(__dirname, "../public/data/schedules");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(
  path.join(outDir, "default_schedules.json"),
  JSON.stringify(groupSchedules, null, 2),
  "utf8"
);

console.log(`Generated ${groupSchedules.length} groups in public/data/schedules/default_schedules.json`);
